---
# tasks file for pre_setup
- name: set timezone to Asia/Tokyo
  community.general.timezone:
    name: Asia/Tokyo

- name: populate service facts
  ansible.builtin.service_facts:

- name: stop firewalld if installed
  ansible.builtin.systemd:
    name: firewalld
    state: stopped
  when: "services.keys()|list|select('search', '^firewalld')|length >0"

- name: install recommended packages
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  loop: 
    - "{{ package_list }}"

- name: download k3s_install script
  ansible.builtin.get_url:
    url: https://get.k3s.io
    dest: /root/k3s_install.sh
    mode: '0755'
    validate_certs: false